# Generated by Django 4.1.3 on 2022-12-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_spam_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spam',
            name='owner',
        ),
    ]
